// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3YIOr3Y5IxbJgX0szwraa1yYq1LK3XgQ',
    appId: '1:955372209936:web:b2ebf1fa1d5aa308448795',
    messagingSenderId: '955372209936',
    projectId: 'final-d2a61',
    authDomain: 'final-d2a61.firebaseapp.com',
    storageBucket: 'final-d2a61.firebasestorage.app',
    measurementId: 'G-RSEYL22FCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZAlNrZcMDd-F10sGyrLn9ValnWs7i8PY',
    appId: '1:955372209936:android:69fe96e5121efd2f448795',
    messagingSenderId: '955372209936',
    projectId: 'final-d2a61',
    storageBucket: 'final-d2a61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnoW-8EFsRl26cS7O7Aa7JYlrWOWi3Dyc',
    appId: '1:955372209936:ios:fd4dffe35582185d448795',
    messagingSenderId: '955372209936',
    projectId: 'final-d2a61',
    storageBucket: 'final-d2a61.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );
}
